export const ALL_INTERESTS = [
  // Home & lifestyle
  "Cooking",
  "Baking",
  "Coffee",
  "Tea",
  "Interior Decorating",
  "Plants/Gardening",
  "DIY/Handy",
  // Habits & routines
  "Early Riser",
  "Night Owl",
  "Clean & Organized",
  "Casual Cleaner",
  "Quiet Evenings",
  "Hosts Occasionally",
  // Food & drink prefs
  "Vegetarian",
  "Vegan",
  "Pescatarian",
  "Omnivore",
  "Wine",
  "Craft Beer",
  // Activities & hobbies
  "Gym/Fitness",
  "Running",
  "Hiking",
  "Cycling",
  "Yoga/Pilates",
  "Board Games",
  "Video Games",
  "Movie Nights",
  "Live Music",
  "Reading",
  "Travel",
  // Work & study
  "Remote Work",
  "Student",
  "Startup/Entrepreneur",
  // Pets
  "Dog Lover",
  "Cat Lover",
];

export const INTERESTS = {
  groupsOrder: [
    "home_lifestyle",
    "habits_routines",
    "food_drink_prefs",
    "activities_hobbies",
    "work_study",
    "pets",
  ],
  groups: {
    home_lifestyle: {
      label: "Home & lifestyle",
      optionsOrder: [
        "cooking",
        "baking",
        "coffee",
        "tea",
        "interior_decorating",
        "plants_gardening",
        "diy_handy",
      ],
      options: {
        cooking: "Cooking",
        baking: "Baking",
        coffee: "Coffee",
        tea: "Tea",
        interior_decorating: "Interior Decorating",
        plants_gardening: "Plants/Gardening",
        diy_handy: "DIY/Handy",
      },
    },
    habits_routines: {
      label: "Habits & routines",
      optionsOrder: [
        "early_riser",
        "night_owl",
        "clean_organized",
        "casual_cleaner",
        "quiet_evenings",
        "hosts_occasionally",
      ],
      options: {
        early_riser: "Early Riser",
        night_owl: "Night Owl",
        clean_organized: "Clean & Organized",
        casual_cleaner: "Casual Cleaner",
        quiet_evenings: "Quiet Evenings",
        hosts_occasionally: "Hosts Occasionally",
      },
    },
    food_drink_prefs: {
      label: "Food & drink prefs",
      optionsOrder: [
        "vegetarian",
        "vegan",
        "pescatarian",
        "omnivore",
        "wine",
        "craft_beer",
      ],
      options: {
        vegetarian: "Vegetarian",
        vegan: "Vegan",
        pescatarian: "Pescatarian",
        omnivore: "Omnivore",
        wine: "Wine",
        craft_beer: "Craft Beer",
      },
    },
    activities_hobbies: {
      label: "Activities & hobbies",
      optionsOrder: [
        "gym_fitness",
        "running",
        "hiking",
        "cycling",
        "yoga_pilates",
        "board_games",
        "video_games",
        "movie_nights",
        "live_music",
        "reading",
        "travel",
      ],
      options: {
        gym_fitness: "Gym/Fitness",
        running: "Running",
        hiking: "Hiking",
        cycling: "Cycling",
        yoga_pilates: "Yoga/Pilates",
        board_games: "Board Games",
        video_games: "Video Games",
        movie_nights: "Movie Nights",
        live_music: "Live Music",
        reading: "Reading",
        travel: "Travel",
      },
    },
    work_study: {
      label: "Work & study",
      optionsOrder: ["remote_work", "student", "startup_entrepreneur"],
      options: {
        remote_work: "Remote Work",
        student: "Student",
        startup_entrepreneur: "Startup/Entrepreneur",
      },
    },
    pets: {
      label: "Pets",
      optionsOrder: ["dog_lover", "cat_lover"],
      options: {
        dog_lover: "Dog Lover",
        cat_lover: "Cat Lover",
      },
    },
  },
};

export const QUIZ = {
  sectionsOrder: [
    "basics",
    "pets",
    "lifestyle",
    "substances",
    "amenities",
    "interests",
    "compatibility",
  ],
  sections: {
    basics: {
      title: "Basics",
      questionsOrder: [
        "budget_range",
        "move_in_timeline",
        "specific_move_in_date",
        "minimum_stay",
        "maximum_stay",
        "lease_duration",
        "room_type",
      ],
      questions: {
        budget_range: {
          type: "slider-range",
          label: "Monthly rent budget",
          min: 300,
          max: 5000,
          step: 25,
          default: [900, 1400],
          format: "currency",
          required: true,
        },
        move_in_timeline: {
          type: "select",
          label: "When are you looking to move?",
          optionsOrder: ["asap_2w", "1m", "2m", "2p", "specific"],
          options: {
            asap_2w: { label: "ASAP (≤ 2 weeks)" },
            "1m": { label: "Within 1 month" },
            "2m": { label: "1–2 months" },
            "2p": { label: "2+ months" },
            specific: { label: "I have a specific date" },
          },
          required: true,
          triggers: { specific: ["specific_move_in_date"] },
        },
        specific_move_in_date: {
          type: "date",
          label: "Pick your ideal move-in date",
          visible_if: { question: "move_in_timeline", equals: "specific" },
        },
        minimum_stay: {
          type: "duration-picker",
          label: "Minimum stay",
          help: "Pick any duration (supports half-years like 18 months / 1.5 years).",
          units: ["months", "years"],
          min_value_months: 1,
          max_value_months: 120,
          step_months: 1,
          presetsOrder: ["1m", "3m", "6m", "12m", "18m", "24m", "36m", "60m"],
          presets: {
            "1m": { months: 1, label: "1 month" },
            "3m": { months: 3, label: "3 months" },
            "6m": { months: 6, label: "6 months" },
            "12m": { months: 12, label: "1 year" },
            "18m": { months: 18, label: "1.5 years" },
            "24m": { months: 24, label: "2 years" },
            "36m": { months: 36, label: "3 years" },
            "60m": { months: 60, label: "5 years" },
          },
          allow_custom: true,
          default_months: 12,
          required: true,
        },
        maximum_stay: {
          type: "duration-picker",
          label: "Maximum stay",
          help: "Pick any duration or set to open-ended.",
          units: ["months", "years"],
          min_value_months: 1,
          max_value_months: 240,
          step_months: 1,
          presetsOrder: ["3m", "6m", "12m", "18m", "24m", "36m", "60m", "open"],
          presets: {
            "3m": { months: 3, label: "Up to 3 months" },
            "6m": { months: 6, label: "Up to 6 months" },
            "12m": { months: 12, label: "Up to 12 months" },
            "18m": { months: 18, label: "Up to 18 months" },
            "24m": { months: 24, label: "Up to 2 years" },
            "36m": { months: 36, label: "Up to 3 years" },
            "60m": { months: 60, label: "Up to 5 years" },
            open: { months: null, label: "Open-ended" },
          },
          allow_custom: true,
          default_months: null,
          required: true,
          validation: {
            rule: "max_gte_min_or_open",
            args: { min_field: "minimum_stay" },
            message:
              "Maximum stay must be greater than or equal to minimum stay (or set to open-ended).",
          },
        },
        lease_duration: {
          type: "select",
          label: "Preferred lease duration",
          optionsOrder: ["3_6", "12", "18p", "mtm", "flex"],
          options: {
            "3_6": { label: "3–6 months" },
            12: { label: "12 months" },
            "18p": { label: "18+ months" },
            mtm: { label: "Month-to-month" },
            flex: { label: "Flexible" },
          },
          required: true,
        },
        room_type: {
          type: "select",
          label: "Room type",
          optionsOrder: ["private", "shared", "either"],
          options: {
            private: { label: "Private room" },
            shared: { label: "Shared room" },
            either: { label: "Either is fine" },
          },
          required: true,
        },
      },
    },

    pets: {
      title: "Pets",
      questionsOrder: [
        "pet_ownership",
        "pet_ownership_details",
        "pet_tolerance",
        "pet_tolerance_other_text",
        "pet_allergies",
        "pet_allergies_other_text",
        "pet_rules",
      ],
      questions: {
        pet_ownership: {
          type: "multi",
          label: "Do you have any pets? (select all that apply)",
          optionsOrder: ["dog", "cat", "small_pet", "other", "none"],
          options: {
            dog: { label: "Dog" },
            cat: { label: "Cat" },
            small_pet: { label: "Small pet (bird/hamster/fish/reptile)" },
            other: { label: "Other (specify)" },
            none: { label: "No pets" },
          },
          exclusive_with: [["none", ["dog", "cat", "small_pet", "other"]]],
          required: true,
        },
        pet_ownership_details: {
          type: "dynamic-group",
          label: "Tell us a bit about your pets",
          visible_if_any_of: {
            pet_ownership: ["dog", "cat", "small_pet", "other"],
          },
          repeat_per_selection_of: "pet_ownership",
          schemas: {
            dog: [
              {
                id: "dog_size",
                type: "select",
                label: "Dog size",
                optionsOrder: ["small", "medium", "large"],
                options: {
                  small: { label: "Small (≤25 lb)" },
                  medium: { label: "Medium (26–50 lb)" },
                  large: { label: "Large (51+ lb)" },
                },
              },
              { id: "dog_training", type: "toggle", label: "House-trained" },
            ],
            cat: [
              {
                id: "cat_type",
                type: "select",
                label: "Cat type",
                optionsOrder: ["indoor", "outdoor", "indoor_outdoor"],
                options: {
                  indoor: { label: "Indoor" },
                  outdoor: { label: "Outdoor" },
                  indoor_outdoor: { label: "Indoor/Outdoor" },
                },
              },
            ],
            small_pet: [
              {
                id: "small_pet_kind",
                type: "text",
                label: "Type (e.g., bird, fish, reptile)",
              },
            ],
            other: [{ id: "other_pet_kind", type: "text", label: "What pet?" }],
          },
        },
        pet_tolerance: {
          type: "multi",
          label: "OK living with roommate’s pets (select all that apply)",
          optionsOrder: [
            "dog_small",
            "dog_large",
            "cat_ok",
            "small_pets_ok",
            "hypo_only",
            "other_ok",
            "no_pets",
          ],
          options: {
            dog_small: { label: "Small dogs (≤25 lb)" },
            dog_large: { label: "Medium/Large dogs (26+ lb)" },
            cat_ok: { label: "Cats" },
            small_pets_ok: { label: "Small pets (caged/tank)" },
            hypo_only: { label: "Hypoallergenic dogs only" },
            other_ok: { label: "Other (specify)" },
            no_pets: { label: "Prefer pet-free home" },
          },
          exclusive_with: [
            [
              "no_pets",
              [
                "dog_small",
                "dog_large",
                "cat_ok",
                "small_pets_ok",
                "hypo_only",
                "other_ok",
              ],
            ],
          ],
          required: true,
        },
        pet_tolerance_other_text: {
          type: "text",
          label: "Other pets you're OK with",
          visible_if_all_of: [
            { question: "pet_tolerance", includes: "other_ok" },
            { question: "pet_tolerance", excludes: "no_pets" },
          ],
        },
        pet_allergies: {
          type: "multi",
          label: "Allergies (select all that apply)",
          optionsOrder: [
            "allergy_dog",
            "allergy_large_dog",
            "allergy_small_dog",
            "allergy_cat",
            "allergy_small_pets",
            "allergy_other",
            "none",
          ],
          options: {
            allergy_dog: { label: "Dogs" },
            allergy_large_dog: { label: "Large dogs" },
            allergy_small_dog: { label: "Small dogs" },
            allergy_cat: { label: "Cats" },
            allergy_small_pets: { label: "Small pets (caged/tank)" },
            allergy_other: { label: "Other (specify)" },
            none: { label: "None" },
          },
          exclusive_with: [
            [
              "none",
              [
                "allergy_dog",
                "allergy_large_dog",
                "allergy_small_dog",
                "allergy_cat",
                "allergy_small_pets",
                "allergy_other",
              ],
            ],
          ],
        },
        pet_allergies_other_text: {
          type: "text",
          label: "Other allergy",
          visible_if: { question: "pet_allergies", includes: "allergy_other" },
        },
        pet_rules: {
          type: "multi",
          label: "Pet-related house rules you prefer",
          optionsOrder: [
            "no_pets_in_bedrooms",
            "extra_cleaning",
            "deposit_ok",
            "pet_meet",
          ],
          options: {
            no_pets_in_bedrooms: { label: "No pets in bedrooms" },
            extra_cleaning: { label: "Extra cleaning for shedding" },
            deposit_ok: { label: "OK with pet deposit/fees" },
            pet_meet: { label: "Pet meet-and-greet first" },
          },
        },
      },
    },

    lifestyle: {
      title: "Lifestyle",
      questionsOrder: [
        "cleanliness_level",
        "cleaning_frequency",
        "home_presence",
        "sleep_rhythm",
        "guest_frequency",
        "overnight_guests",
        "noise_tolerance",
      ],
      questions: {
        cleanliness_level: {
          type: "scale",
          label: "Cleanliness standard (shared spaces)",
          min: 1,
          max: 5,
          anchors: { left: "Lived-in", right: "Spotless" },
          required: true,
        },
        cleaning_frequency: {
          type: "scale",
          label: "How often you clean shared areas",
          min: 1,
          max: 5,
          anchors: { left: "Monthly", right: "Daily" },
          required: true,
        },
        home_presence: {
          type: "select",
          label: "You’re typically…",
          optionsOrder: ["mostly_home", "hybrid", "mostly_out"],
          options: {
            mostly_home: { label: "Home most days (WFH/remote)" },
            hybrid: { label: "Hybrid (some days out)" },
            mostly_out: { label: "Out most days (on-site/travel)" },
          },
          required: true,
        },
        sleep_rhythm: {
          type: "select",
          label: "Daily rhythm",
          optionsOrder: ["early", "night", "flex"],
          options: {
            early: { label: "Early bird" },
            night: { label: "Night owl" },
            flex: { label: "Flexible / varies" },
          },
          required: true,
        },
        guest_frequency: {
          type: "select",
          label: "Friends over (per week)",
          optionsOrder: ["rare", "weekly", "often"],
          options: {
            rare: { label: "Rarely (≤1)" },
            weekly: { label: "Weekly (2–3)" },
            often: { label: "Often (4+)" },
          },
          required: true,
        },
        overnight_guests: {
          type: "select",
          label: "Overnight guests",
          optionsOrder: ["no", "monthly", "weekly"],
          options: {
            no: { label: "Prefer none" },
            monthly: { label: "Occasional (≤2/mo)" },
            weekly: { label: "Regular (weekly OK)" },
          },
          required: true,
        },
        noise_tolerance: {
          type: "scale",
          label: "Noise tolerance at home",
          min: 1,
          max: 5,
          anchors: { left: "Very quiet", right: "Don’t mind activity" },
          required: true,
        },
      },
    },

    substances: {
      title: "Smoking / Drinking",
      questionsOrder: [
        "smoking_policy",
        "alcohol_use",
        "cannabis_policy",
        "substance_free_preference",
      ],
      questions: {
        smoking_policy: {
          type: "select",
          label: "Smoking / vaping at home",
          optionsOrder: [
            "non_smoker",
            "smoker_outside",
            "smoker_inside",
            "tolerant",
          ],
          options: {
            non_smoker: {
              label: "I don’t smoke/vape and prefer smoke-free home",
            },
            smoker_outside: { label: "I smoke/vape but only outside" },
            smoker_inside: { label: "I smoke/vape indoors" },
            tolerant: { label: "I don’t smoke, but I’m okay with it at home" },
          },
          required: true,
        },
        alcohol_use: {
          type: "select",
          label: "Alcohol at home",
          optionsOrder: [
            "non_drinker",
            "social_drinker",
            "regular_drinker",
            "tolerant",
          ],
          options: {
            non_drinker: {
              label: "I don’t drink and prefer alcohol-free home",
            },
            social_drinker: { label: "Socially (weekends/occasions)" },
            regular_drinker: { label: "Regularly at home" },
            tolerant: { label: "I don’t drink, but I’m okay with it at home" },
          },
          required: true,
        },
        cannabis_policy: {
          type: "select",
          label: "Cannabis (where legal)",
          optionsOrder: ["no_cannabis", "ok_outside", "ok_inside"],
          options: {
            no_cannabis: { label: "Prefer cannabis-free home" },
            ok_outside: { label: "OK if used outside only" },
            ok_inside: { label: "OK indoors" },
          },
        },
        substance_free_preference: {
          type: "toggle",
          label: "I want a substance-free household",
        },
      },
    },

    amenities: {
      title: "Preferred Amenities",
      questionsOrder: [
        "bathroom_pref",
        "laundry",
        "parking",
        "furnishing",
        "extras",
      ],
      questions: {
        bathroom_pref: {
          type: "select",
          label: "Bathroom",
          optionsOrder: ["private_bath", "shared_ok"],
          options: {
            private_bath: { label: "Private bathroom" },
            shared_ok: { label: "Shared bathroom OK" },
          },
        },
        // 🔧 Schema patch (add this under QUIZ.sections.amenities.questions)
        room_preferences: {
          type: "multi",
          label: "What matters most for your room?",
          optionsOrder: [
            "private_bath",
            "master_suite",
            "shared_bath_ok",
            "size_matters",
            "cozy_ok",
            "furnished",
          ],
          options: {
            private_bath: { label: "Private bathroom" },
            master_suite: { label: "Master bedroom" },
            shared_bath_ok: { label: "Shared bathroom is fine" },
            size_matters: { label: "Large room preferred" },
            cozy_ok: { label: "Cozy room is fine" },
            furnished: { label: "Furnished preferred" },
          },
          max: 6,
        },
        laundry: {
          type: "select",
          label: "Laundry",
          optionsOrder: ["in_unit", "in_building", "no_pref"],
          options: {
            in_unit: { label: "In-unit laundry" },
            in_building: { label: "In-building laundry" },
            no_pref: { label: "No preference" },
          },
        },
        parking: {
          type: "select",
          label: "Parking",
          optionsOrder: ["included", "street_ok", "not_needed"],
          options: {
            included: { label: "Dedicated spot" },
            street_ok: { label: "Street/permit OK" },
            not_needed: { label: "Don’t need parking" },
          },
        },
        furnishing: {
          type: "select",
          label: "Furnishing",
          optionsOrder: ["furnished", "unfurnished", "either"],
          options: {
            furnished: { label: "Furnished preferred" },
            unfurnished: { label: "Unfurnished OK" },
            either: { label: "Either is fine" },
          },
        },
        extras: {
          type: "multi",
          label: "Nice-to-haves",
          optionsOrder: ["balcony", "gym", "ac", "updated", "outdoor_space"],
          options: {
            balcony: { label: "Balcony/patio" },
            gym: { label: "Gym in building" },
            ac: { label: "Air conditioning" },
            updated: { label: "Modern/updated unit" },
            outdoor_space: { label: "Yard/shared outdoor space" },
          },
        },
      },
    },

    interests: {
      title: "Interests",
      questionsOrder: [
        "interests_active",
        "interests_arts_media",
        "interests_at_home",
        "interests_social",
        "interests_gaming_tech",
      ],
      questions: {
        interests_active: {
          type: "chips",
          label: "Active",
          optionsOrder: [
            "gym_fitness",
            "running",
            "hiking",
            "cycling",
            "yoga_pilates",
            "team_sports",
          ],
          options: {
            gym_fitness: "Gym/Fitness",
            running: "Running",
            hiking: "Hiking",
            cycling: "Cycling",
            yoga_pilates: "Yoga/Pilates",
            team_sports: "Team Sports",
          },
          max: 5,
        },
        interests_arts_media: {
          type: "chips",
          label: "Arts & Media",
          optionsOrder: [
            "music",
            "live_music",
            "photography",
            "reading",
            "writing",
            "films",
          ],
          options: {
            music: "Music",
            live_music: "Live Music",
            photography: "Photography",
            reading: "Reading",
            writing: "Writing",
            films: "Films",
          },
          max: 5,
        },
        interests_at_home: {
          type: "chips",
          label: "At-home hobbies",
          optionsOrder: [
            "cooking",
            "baking",
            "coffee",
            "board_games",
            "crafts_diy",
            "plants_gardening",
          ],
          options: {
            cooking: "Cooking",
            baking: "Baking",
            coffee: "Coffee",
            board_games: "Board Games",
            crafts_diy: "Crafts/DIY",
            plants_gardening: "Plants/Gardening",
          },
          max: 5,
        },
        interests_social: {
          type: "chips",
          label: "Social",
          optionsOrder: [
            "game_nights",
            "movie_nights",
            "bar_hopping",
            "brunch",
            "travel",
          ],
          options: {
            game_nights: "Game Nights",
            movie_nights: "Movie Nights",
            bar_hopping: "Bar Hopping",
            brunch: "Brunch",
            travel: "Travel",
          },
          max: 5,
        },
        interests_gaming_tech: {
          type: "chips",
          label: "Gaming & Tech",
          optionsOrder: [
            "console_gaming",
            "pc_gaming",
            "esports",
            "coding",
            "startups_entrepreneur",
          ],
          options: {
            console_gaming: "Console Gaming",
            pc_gaming: "PC Gaming",
            esports: "Esports",
            coding: "Coding",
            startups_entrepreneur: "Startups/Entrepreneur",
          },
          max: 5,
        },
      },
    },

    compatibility: {
      title: "Compatibility & House Rules",
      questionsOrder: [
        "quiet_hours",
        "chore_system",
        "communication_style",
        "thermostat_pref",
        "compatible_with",
      ],
      questions: {
        quiet_hours: {
          type: "select",
          label: "Preferred quiet hours",
          optionsOrder: ["22_07", "23_08", "flex"],
          options: {
            "22_07": { label: "10pm–7am" },
            "23_08": { label: "11pm–8am" },
            flex: { label: "Flexible / discuss" },
          },
        },
        chore_system: {
          type: "select",
          label: "Chore system you prefer",
          optionsOrder: ["rota", "zones", "split", "outsourced"],
          options: {
            rota: { label: "Rotation schedule" },
            zones: { label: "Zones/ownership" },
            split: { label: "Split by preference" },
            outsourced: { label: "Hire cleaner monthly" },
          },
        },
        communication_style: {
          type: "select",
          label: "How should we handle small issues?",
          optionsOrder: ["text", "in_person", "shared_board"],
          options: {
            text: { label: "Text first" },
            in_person: { label: "Quick in-person chat" },
            shared_board: { label: "Shared notes/board" },
          },
        },
        thermostat_pref: {
          type: "select",
          label: "Preferred indoor temperature",
          optionsOrder: ["cool", "mid", "warm", "flex"],
          options: {
            cool: { label: "67–70°F" },
            mid: { label: "70–73°F" },
            warm: { label: "73–76°F" },
            flex: { label: "Flexible" },
          },
        },
        compatible_with: {
          type: "chips",
          label: "You’re most compatible with…",
          optionsOrder: [
            "non_smokers",
            "pet_owners",
            "early_risers",
            "night_owls",
            "students",
            "professionals",
            "remote_workers",
            "quiet_household",
            "social_household",
          ],
          options: {
            non_smokers: "Non-smokers",
            pet_owners: "Pet owners",
            early_risers: "Early risers",
            night_owls: "Night owls",
            students: "Students",
            professionals: "Professionals",
            remote_workers: "Remote workers",
            quiet_household: "Quiet household",
            social_household: "Social household",
          },
          max: 6,
        },
      },
    },
  },
};
